title: Chhayly Lim
description: AI/Software Engineer & Educator
url: "https://aicambodia.space"
baseurl: ""

# Custom domain
domain: aicambodia.space
cname: aicambodia.space

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-github-metadata

github: []